/**
 * The work page's gallery, curated. 6 September 2026.
 *
 * WHY THIS FILE EXISTS. Until today /work/ built itself: six categories, one
 * carousel each, every photograph in the selection shown. Kaspar's instruction
 * after reviewing the preview ends that. There is not yet enough strong
 * photography in every category for six of them to hold up, so the categories
 * come off and the strongest work goes into one continuous gallery, with
 * several similar photographs of the same job cut down to the best one. When
 * the library is deeper, filtering can come back.
 *
 * So the selection is no longer a rule a script can apply. `_selection.json`
 * says which photographs are usable, which is a quality-and-provenance
 * judgement made at triage; this file says which are worth showing next to
 * each other, which is an editorial one. They are different questions and they
 * belong in different files. `_selection.json` is regenerated by the triage
 * script and would overwrite anything written into it.
 *
 * THE ORDER IS DELIBERATE. No two neighbours are the same type of work, so the
 * page reads as a body of work rather than as the six categories it used to
 * be, laid end to end. Every file here is in `_selection.json`; work.astro
 * looks up its real dimensions there and fails the build if one is missing.
 *
 * -------------------------------------------------------------------------
 * THE THIRTEEN THAT ARE NOT HERE, and why. Every one is still in
 * `_selection.json`, so putting one back is a line in this array.
 *
 *   fitted-wardrobes-01, -04, -05,  four empty oak-lined cavities, two of them
 *   -06                             13 seconds apart. -05 was in the gallery
 *                                   for one build, as the interior that shows
 *                                   the drawer bank, and rendering it settled
 *                                   it: at 1400 x 1867 it is the tallest frame
 *                                   in the masonry and an empty carcass had
 *                                   the most weight on the page. A frame's
 *                                   size here is its shape, not its merit, so
 *                                   the weakest photograph cannot be a tall
 *                                   one.
 *   fitted-wardrobes-07             the same white run as -02, eight seconds
 *                                   later. -02 has the room in it.
 *   walk-in-wardrobes-02            underlit corner, and the only quality-4
 *                                   frame of the three walk-in shots.
 *   alcove-units-02                 empty shelving, unstyled, in a set where
 *                                   every other frame is a finished room.
 *   bespoke-kitchens-02, -03        portrait crops of the same grey marble
 *                                   kitchen as -01.
 *   bespoke-kitchens-05             grey and stainless, weakest kitchen.
 *   bespoke-kitchens-06, -08        the same sage-green kitchen as -07, shot
 *                                   from the living room, where the kitchen is
 *                                   a quarter of the frame. -08 is also the
 *                                   About page photograph.
 *   doors-panelling-03              an exterior front door, and the only frame
 *                                   here that is not fitted furniture inside a
 *                                   home.
 *
 * -------------------------------------------------------------------------
 * THE TYPE LABELS are what a visitor reads under each frame, and they are the
 * plain description Kaspar asked for rather than a caption: what the work is,
 * and nothing about the room, the client or the address. Real captions need
 * Q44 to Q49, which are still open.
 *
 * "Built-in TV units", never "media wall": protocol section 5 allows the
 * search phrase on its own page and nowhere else, and this is nowhere else.
 */
export type WorkShot = {
  /** Must match a `file` in public/images/_selection.json. */
  file: string;
  /** The plain description under the frame. */
  type: string;
};

export const WORK_GALLERY: WorkShot[] = [
  { file: "/images/alcove-units/alcove-units-01.webp", type: "Alcove units" },
  { file: "/images/fitted-wardrobes/fitted-wardrobes-03.webp", type: "Fitted wardrobes" },
  { file: "/images/media-walls/media-walls-01.webp", type: "Built-in TV units" },
  { file: "/images/bespoke-kitchens/kitchen-shaker-showpiece.webp", type: "Bespoke kitchens" },
  { file: "/images/walk-in-wardrobes/walk-in-wardrobes-01.webp", type: "Walk-in wardrobes" },
  { file: "/images/doors-panelling/doors-panelling-02.webp", type: "Panelling and doors" },
  { file: "/images/alcove-units/alcove-units-06.webp", type: "Alcove units" },
  { file: "/images/fitted-wardrobes/fitted-wardrobes-02.webp", type: "Fitted wardrobes" },
  { file: "/images/bespoke-kitchens/bespoke-kitchens-01.webp", type: "Bespoke kitchens" },
  { file: "/images/media-walls/media-walls-02.webp", type: "Built-in TV units" },
  { file: "/images/alcove-units/alcove-units-03.webp", type: "Alcove units" },
  { file: "/images/walk-in-wardrobes/walk-in-wardrobes-03.webp", type: "Walk-in wardrobes" },
  { file: "/images/bespoke-kitchens/bespoke-kitchens-07.webp", type: "Bespoke kitchens" },
  { file: "/images/alcove-units/alcove-units-05.webp", type: "Alcove units" },
  { file: "/images/media-walls/media-walls-03.webp", type: "Built-in TV units" },
  { file: "/images/fitted-wardrobes/fitted-wardrobes-08.webp", type: "Fitted wardrobes" },
  { file: "/images/alcove-units/alcove-units-07.webp", type: "Alcove units" },
  { file: "/images/bespoke-kitchens/bespoke-kitchens-04.webp", type: "Bespoke kitchens" },
  { file: "/images/doors-panelling/doors-panelling-01.webp", type: "Panelling and doors" },
  { file: "/images/alcove-units/alcove-units-04.webp", type: "Alcove units" },
  { file: "/images/media-walls/media-walls-04.webp", type: "Built-in TV units" },
];
