/**
 * The work page's gallery, curated. 6 September 2026.
 *
 * WHY THIS FILE EXISTS. Until today /work/ built itself: six categories, one
 * carousel each, every photograph in the selection shown. Kaspar's instruction
 * after reviewing the preview ends that. There is not yet enough strong
 * photography in every category for six of them to hold up, so the categories
 * come off and the strongest work goes into one continuous gallery, with
 * several similar photographs of the same job cut down to the best one. When
 * the library is deeper, filtering can come back.
 *
 * So the selection is no longer a rule a script can apply. `_selection.json`
 * says which photographs are usable, which is a quality-and-provenance
 * judgement made at triage; this file says which are worth showing next to
 * each other, which is an editorial one. They are different questions and they
 * belong in different files. `_selection.json` is regenerated by the triage
 * script and would overwrite anything written into it.
 *
 * THE ORDER IS DELIBERATE. No two neighbours are the same type of work, so the
 * page reads as a body of work rather than as the six categories it used to
 * be, laid end to end. Every file here is in `_selection.json`; work.astro
 * looks up its real dimensions there and fails the build if one is missing.
 *
 * -------------------------------------------------------------------------
 * FOUR MORE FRAMES, 8 September 2026, afternoon. Denis sent eight photographs
 * and asked for any not on this page to be added. Twenty became twenty-four.
 * Each of the eight, against what was here:
 *
 *   the white handleless kitchen with the marble worktop and herringbone
 *   floor: NOT HERE, and not in the library either. It is the old site's own
 *   portfolio image (modern-handleless-kitchen-hackney-london.jpg, 1600 wide,
 *   EXIF stripped), so it is his work and his photograph; it is now
 *   bespoke-kitchens-09, registered in _selection.json by hand with the
 *   capture date left blank because nothing records it.
 *   the lit bookcase wall, front-on: the room is here as alcove-units-09 (the
 *   angled frame); this front-on view is alcove-units-02, cut in the first
 *   pass. Not added: a second angle of a room already on the page.
 *   the lit bookcase wall, angled: alcove-units-09, already here.
 *   the walk-in with the black drawer handles: the room is here as
 *   walk-in-wardrobes-01; this is a third angle. Not added, same reason.
 *   the corner library mid-install, doors laid out for painting: NOT ADDED.
 *   Work in progress is not publishable (tone protocol section 15,
 *   photography), whatever the instruction.
 *   the navy loft wardrobe with its doors open: NOT HERE. Library file
 *   20250522_085815.jpg, the same room as fitted-wardrobes-03 (slot 17), the
 *   morning of the same day, doors open on the lit interior. Now
 *   fitted-wardrobes-10, two slots after its closed-door pair. The carpet is
 *   still under protective sheeting in this frame.
 *   the oak interior with the seven-drawer stack: fitted-wardrobes-05, cut in
 *   the first pass as an empty carcass. Back on Denis's instruction.
 *   the oak interior with four drawers and the green room beyond:
 *   fitted-wardrobes-04, cut for the same reason. Back likewise.
 *
 * So two of the eight were already here, two are second angles of rooms
 * already here, one cannot go up, and three came in plus one from the old
 * site. The no-two-neighbours rule holds through the new tail. The first-cut
 * judgment about empty oak cavities below still stands as a judgment; these
 * two are on the page because the client's side asked for them, which is a
 * different reason, and the record should say which.
 *
 * -------------------------------------------------------------------------
 * THE WARDROBE TILE, 7 September 2026, evening. Kaspar, under a screenshot of
 * the homepage's Selected work grid: "here at fitted wardrobes i would put one
 * of the latest pics". The grid is the first six frames of this array, so the
 * second slot changed hands: fitted-wardrobes-08 (20260527_125257, the
 * green-walled house's white handleless run, 27 May 2026, the newest wardrobe
 * job the library holds) moved up from slot 17, and fitted-wardrobes-03 (the
 * navy loft wardrobe, May 2025) moved down to where -08 was. A swap rather
 * than an addition, so the gallery stays at twenty with one frame per room,
 * and both slots keep the no-two-neighbours-alike rule because the type is
 * the same at either end. "Latest" was read as the most recent job by
 * capture date; the professional frame, -09 (DSC_6584), was shot in October
 * 2024 and stays at slot 14.
 *
 * -------------------------------------------------------------------------
 * THIRD PASS, 7 September 2026, on Denis asking for the gallery to be enriched
 * "with no duplicates, just original photos". Sixteen became twenty, and the
 * way to get there was to go past the site's 34-frame selection into the
 * library itself: 60 finished frames at quality 4 or better were not on the
 * site, and the file timestamps sorted them into rooms. Almost all were more
 * angles of rooms already here (the grey marble kitchen eight times, the one
 * walk-in twelve times, the green-walled house's wardrobes eleven times). Five
 * were rooms the gallery did not have:
 *
 *   fitted-wardrobes-09   DSC_6584, the professional frame of a white built-in
 *                         wardrobe run in a bedroom, from the 31 Aug drop. The
 *                         library note of that day says it led the wardrobe
 *                         page; the 4 Sep renumbering lost it and nobody
 *                         noticed. Back, as its own file.
 *   alcove-units-08       IMG-20260216-WA0011, painted alcove cupboards either
 *                         side of a herringbone-tiled fireplace, TV above.
 *                         February 2026, the newest finished room in the
 *                         library.
 *   alcove-units-09       20251212_152708, a lit white bookcase wall in an
 *                         empty room. The same room as alcove-units-02, which
 *                         the first cut left out as unstyled; this frame is
 *                         lit and front-on and reads as the piece it is.
 *   walk-in-wardrobes-02  back from the first cut: a dark-timber corner
 *                         walk-in, a different project from -01.
 *   bespoke-kitchens-05   back from the first cut: the grey gloss kitchen,
 *                         DSC_9770, a different project from every other
 *                         kitchen here.
 *
 * TWO FILES ARE REPLACED BY THEIR ORIGINALS. fitted-wardrobes-03 and -08 were
 * built from "(1)" exports, which the library rules exclude as AI-edited
 * copies. No label was visible on either at full size, but the originals
 * exist and there is no reason to carry the risk: -03 is now
 * 20250522_171826.jpg, the same navy loft wardrobe, and -08 is now
 * 20260527_125257.jpg, the corner view of the same white run, which is the
 * better frame of that room in any case.
 *
 * AND ONE MORE DUPLICATE CAME OUT. media-walls-02 and -03 are one house, six
 * days apart: the fireplace in -03's furnished room is the fireplace beyond
 * the corner unit in -02's empty one. The lit corner unit stays, at quality 5.
 *
 * What is still in the library and not here, and why: the green door
 * (exterior, and the page says interior joinery); the whole-room frames of the
 * green-kitchen flat (that flat is here three times already); every other
 * angle of a room above.
 *
 * -------------------------------------------------------------------------
 * SECOND CUT, later on 6 September 2026, on Denis asking for the duplicates
 * to come out. Twenty-one became sixteen. The first pass was made from a
 * contact sheet of thumbnails, and thumbnails hide two things: that two files
 * are one photograph, and that two photographs are one room. A perceptual
 * hash across every pair caught the first (2 bits apart in 256, the next
 * closest pair 88); the same frames laid out at a size the eye can judge
 * caught the rest, by the rug, the lamp, the chair and the floor.
 *
 *   bespoke-kitchens-04             the same photograph as
 *                                   kitchen-shaker-showpiece, under a second
 *                                   name. Both were in the gallery.
 *   alcove-units-04, media-walls-04 the same living room as alcove-units-05,
 *                                   from the bay and from the door: same
 *                                   herringbone floor, same diamond rug, same
 *                                   coffee table, same white units.
 *                                   alcove-units-05 is the best composed of
 *                                   the three and stays.
 *   alcove-units-06                 the same fireplace as alcove-units-07,
 *                                   wide: same black surround, same yellow
 *                                   lamp, same blue-cushioned chair. -07 is
 *                                   the tighter, better-lit shot of the
 *                                   joinery and stays.
 *   walk-in-wardrobes-03            the other side of the room in
 *                                   walk-in-wardrobes-01, two minutes later.
 *                                   Kaspar's rule is the strongest frame per
 *                                   project, and this is his thinnest set, so
 *                                   it is the first to put back when he
 *                                   photographs another walk-in.
 *
 * -------------------------------------------------------------------------
 * THE THIRTEEN FROM THE FIRST CUT, and why. Every one is still in
 * `_selection.json`, so putting one back is a line in this array.
 *
 *   fitted-wardrobes-01, -04, -05,  four empty oak-lined cavities, two of them
 *   -06                             13 seconds apart. -05 was in the gallery
 *                                   for one build, as the interior that shows
 *                                   the drawer bank, and rendering it settled
 *                                   it: at 1400 x 1867 it is the tallest frame
 *                                   in the masonry and an empty carcass had
 *                                   the most weight on the page. A frame's
 *                                   size here is its shape, not its merit, so
 *                                   the weakest photograph cannot be a tall
 *                                   one.
 *   fitted-wardrobes-07             the same white run as -02, eight seconds
 *                                   later. -02 has the room in it.
 *   walk-in-wardrobes-02            underlit corner, and the only quality-4
 *                                   frame of the three walk-in shots.
 *   alcove-units-02                 empty shelving, unstyled, in a set where
 *                                   every other frame is a finished room.
 *   bespoke-kitchens-02, -03        portrait crops of the same grey marble
 *                                   kitchen as -01.
 *   bespoke-kitchens-05             grey and stainless, weakest kitchen.
 *   bespoke-kitchens-06, -08        the same sage-green kitchen as -07, shot
 *                                   from the living room, where the kitchen is
 *                                   a quarter of the frame. -08 is also the
 *                                   About page photograph.
 *   doors-panelling-03              an exterior front door, and the only frame
 *                                   here that is not fitted furniture inside a
 *                                   home.
 *
 * -------------------------------------------------------------------------
 * THE TYPE LABELS are what a visitor reads under each frame, and they are the
 * plain description Kaspar asked for rather than a caption: what the work is,
 * and nothing about the room, the client or the address. Real captions need
 * Q44 to Q49, which are still open.
 *
 * "Built-in TV units", never "media wall": protocol section 5 allows the
 * search phrase on its own page and nowhere else, and this is nowhere else.
 */
export type WorkShot = {
  /** Must match a `file` in public/images/_selection.json. */
  file: string;
  /** The plain description under the frame. */
  type: string;
};

export const WORK_GALLERY: WorkShot[] = [
  { file: "/images/alcove-units/alcove-units-01.webp", type: "Alcove units" },
  { file: "/images/fitted-wardrobes/fitted-wardrobes-08.webp", type: "Fitted wardrobes" },
  { file: "/images/media-walls/media-walls-01.webp", type: "Built-in TV units" },
  { file: "/images/bespoke-kitchens/kitchen-shaker-showpiece.webp", type: "Bespoke kitchens" },
  { file: "/images/walk-in-wardrobes/walk-in-wardrobes-01.webp", type: "Walk-in wardrobes" },
  { file: "/images/doors-panelling/doors-panelling-02.webp", type: "Panelling and doors" },
  { file: "/images/alcove-units/alcove-units-08.webp", type: "Alcove units" },
  { file: "/images/fitted-wardrobes/fitted-wardrobes-02.webp", type: "Fitted wardrobes" },
  { file: "/images/bespoke-kitchens/bespoke-kitchens-01.webp", type: "Bespoke kitchens" },
  { file: "/images/alcove-units/alcove-units-03.webp", type: "Alcove units" },
  { file: "/images/walk-in-wardrobes/walk-in-wardrobes-02.webp", type: "Walk-in wardrobes" },
  { file: "/images/media-walls/media-walls-02.webp", type: "Built-in TV units" },
  { file: "/images/alcove-units/alcove-units-05.webp", type: "Alcove units" },
  { file: "/images/fitted-wardrobes/fitted-wardrobes-09.webp", type: "Fitted wardrobes" },
  { file: "/images/bespoke-kitchens/bespoke-kitchens-07.webp", type: "Bespoke kitchens" },
  { file: "/images/alcove-units/alcove-units-09.webp", type: "Alcove units" },
  { file: "/images/fitted-wardrobes/fitted-wardrobes-03.webp", type: "Fitted wardrobes" },
  { file: "/images/bespoke-kitchens/bespoke-kitchens-05.webp", type: "Bespoke kitchens" },
  { file: "/images/fitted-wardrobes/fitted-wardrobes-10.webp", type: "Fitted wardrobes" },
  { file: "/images/alcove-units/alcove-units-07.webp", type: "Alcove units" },
  { file: "/images/doors-panelling/doors-panelling-01.webp", type: "Panelling and doors" },
  { file: "/images/fitted-wardrobes/fitted-wardrobes-05.webp", type: "Fitted wardrobes" },
  { file: "/images/bespoke-kitchens/bespoke-kitchens-09.webp", type: "Bespoke kitchens" },
  { file: "/images/fitted-wardrobes/fitted-wardrobes-04.webp", type: "Fitted wardrobes" },
];
